### PR TITLE
Bug 2072439: Get subnet information from subnet instead of from network addresses 

### PR DESCRIPTION
**Pull request by andreaskaris**
Prior to this change, we retrieved the addresses for subnets from
virtualNetwork.AddressSpace.AddressPrefixes. Now, check the list of
subnets first. If a subnet with the subnet name is found, then use
that instead of virtualNetwork.AddressSpace.AddressPrefixes which
only contains the main subnet's (=masters') address prefixes.

See https://bugzilla.redhat.com/show_bug.cgi?id=2072439 for the issue description.

### CODE REVIEW

**Comment by andreaskaris** [comment]
The only potential problem that I see here might be IPv6 / DualStack. I couldn't test this (cluster bot wouldn't let me spawn dualstack :-/ )

**Comment by andreaskaris** [comment]
After the patch:
~~~
[akaris@linux origin (egressip-tests-option3)]$ oc get nodes -o yaml | grep egress
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-master-0-nic","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":255}}]'
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-master-1-nic","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":255}}]'
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-master-2-nic","ifaddr":{"ipv4":"10.0.0.0/17"},"capacity":{"ip":255}}]'
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-worker-eastus1-lj7rm-nic","ifaddr":{"ipv4":"10.0.128.0/17"},"capacity":{"ip":255}}]'
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-worker-eastus2-x95f7-nic","ifaddr":{"ipv4":"10.0.128.0/17"},"capacity":{"ip":255}}]'
      cloud.network.openshift.io/egress-ipconfig: '[{"interface":"ci-ln-86v09d2-1d09d-dgn8t-worker-eastus3-z4r9p-nic","ifaddr":{"ipv4":"10.0.128.0/17"},"capacity":{"ip":255}}]'
~~~

**Comment by andreaskaris** [comment]
/test e2e-azure
flake

**Comment by kyrtapz** [comment]
/lgtm
NIT: main subnet isn't actually equal to master subnet, right?
`10.0.0.0/16` vs `10.0.0.0/17`

**Comment by andreaskaris** [comment]
> /lgtm NIT: main subnet isn't actually equal to master subnet, right? `10.0.0.0/16` vs `10.0.0.0/17`

Good catch, so they just split the /16 in the middle and reserve the first /17 for the masters, and the last /17 for the workers.

**Comment by flavio-fernandes** [comment]
/lgtm
TY @andreaskaris !

**Pull request merged**
