### PR TITLE
[release-4.11] OCPBUGS-3932: Add assigned egress ips into capacity

### PR DESCRIPTION
**Pull request by pperiyasamy**
This is manual cherry-pick of https://github.com/openshift/cloud-network-config-controller/pull/73.

Resolved conflicts:
https://github.com/openshift/cloud-network-config-controller/pull/78/commits/94a5b016982e1cd463d5de4efe151f9ad1294911: `go.mod`, `go.sum` and `vendor` directory
https://github.com/openshift/cloud-network-config-controller/pull/78/commits/1eaff10ba226ff197ec525c765585c4a8b963e62: `pkg/controller/node/node_controller.go`, `pkg/cloudprovider/aws.go`, `pkg/cloudprovider/openstack.go` and `pkg/cloudprovider/openstack_test.go`

/assign @andreaskaris @kyrtapz

### CODE REVIEW

**Comment by kyrtapz** [comment]
Please use `git cherry-pick -x` for both commits.
Was there any conflicts? Is there a reason you didn't use the cherry-pick bot?

**Comment by pperiyasamy** [comment]
> Please use `git cherry-pick -x` for both commits.
> Was there any conflicts? Is there a reason you didn't use the cherry-pick bot?

Yes @kyrtapz, `git cherry-pick` created too many conflicts for this [commit](https://github.com/openshift/cloud-network-config-controller/pull/78/commits/0994a337a710876737ed31a775d91b19eb2cd306) because of version changes, hence this commit is done without cherry-pick. is that fine ?

**Comment by pperiyasamy** [comment]
> > Please use `git cherry-pick -x` for both commits.
> > Was there any conflicts? Is there a reason you didn't use the cherry-pick bot?
> 
> Yes @kyrtapz, `git cherry-pick` created too many conflicts for this [commit](https://github.com/openshift/cloud-network-config-controller/pull/78/commits/0994a337a710876737ed31a775d91b19eb2cd306) because of version changes, hence this commit is done without cherry-pick. is that fine ?

@kyrtapz as discussed offline, `git cherry-pick -x` is used for both commits now.

**Comment by andreaskaris** [comment]
/lgtm I compared 6a22336fcf9d4f6e3b9aa68acba3d00ea8f6eed1 against 8ffb0c15d73f339980cb6fa15fe6c04eab914d12 and other than the missing OSP stuff, it looks exactly the same as the original
nit: I would have added that to the Conflicts: section in the PR directly but no biggy

**Pull request merged**
