### PR TITLE
[release-4.11] OCPBUGS-4167: Run azure operations in sequence

### PR DESCRIPTION
**Pull request by kyrtapz**
This is a clean cherry-pick of https://github.com/openshift/cloud-network-config-controller/pull/52  and a log fix.

/cc @pperiyasamy @andreaskaris

### CODE REVIEW

**Comment by andreaskaris** [comment]
/hold
Doesn't the log fix first have to merge into 4.12?

**Comment by kyrtapz** [comment]
> /hold Doesn't the log fix first have to merge into 4.12?

Yup: https://github.com/openshift/cloud-network-config-controller/pull/80

**Pull request merged**
