### PR TITLE
azure: use azidentity with an adapter

### PR DESCRIPTION
**Pull request by r4f4**
ADAL is being deprecated, so we should move to azidentity.

WIP while I test Azure StackCloud.

### CODE REVIEW

**Comment by r4f4** [comment]
/retitle azure: use azidentity with an adapter

**Comment by r4f4** [comment]
Fixed a typo `s/HasPrefix/HasSuffix/`

**Comment by r4f4** [comment]
Context for this change: https://issues.redhat.com/browse/CORS-2466
@kyrtapz What is missing to get this merged?

**Comment by kyrtapz** [comment]
Thanks for the pr @r4f4 
/lgtm

**Pull request merged**
