### PR TITLE
[release-4.12] OCPBUGS-13802: sync CloudPrivateIpConfig when node is missing

### PR DESCRIPTION
**Pull request by jluhrsen**
in the case that an egressIP is assigned to a node and that node is deleted, the sync will not be able to Get() that node but we still need to release
that IP and be able assign that to another node
in the egressIP object. The machine must be deleted as well, although that should be what triggers
the node delete.

### CODE REVIEW

**Comment by jluhrsen** [comment]
I have tested this locally and verified it works as expected.

**Comment by kyrtapz** [comment]
@jluhrsen unit tests are failing :( 
When there are conflicts during backports it is good to mention them in the commit/pr description. It allows reviewers to focus on those areas. 

/retitle [release-4.12] OCPBUGS-13802: sync CloudPrivateIpConfig when node is missing

**Comment by jluhrsen** [comment]
retest

**Pull request merged**
